// Catalogue public et non exhaustif. Aucun inventaire de parcelle n'est embarqué.
// Les périodes propres à une variété restent null si la source ne les donne pas.
export const varietySources = [
 {id:'IN-POM',title:'Fil d’Ariane : création de variétés de pommes',url:'https://www.inrae.fr/index.php/actualites/fil-dariane-creer-nouvelles-varietes-pommes-agriculture-durable',publisher:'INRAE',kind:'Recherche variétale',scope:'Ariane, Story Inored, Belchard Chantecler, Florina Querina, Antarès Dalinbel et Choupette Dalinette ; floraison et maturité d’Ariane relatives à Golden.',why:'Présentation des obtentions et de leur sélection par l’organisme de recherche.',limit:'Les résistances peuvent être contournées ; les repères relatifs ne donnent pas de date locale.',location:'Obtention de la variété Ariane, « Quelques caractéristiques d’Ariane » et recherches sur les résistances'},
 {id:'IN-POI',title:'Création variétale fruitière à Angers',url:'https://irhs.angers-nantes.hub.inrae.fr/la-science-et-vous/creations-varietales/creation-varietale',publisher:'INRAE · IRHS',kind:'Recherche variétale',scope:'Poires Angys et Migo.',why:'Liste institutionnelle d’obtentions fruitières.',limit:'Les caractères culturaux et calendriers ne sont pas détaillés sur cette page.',location:'Paragraphe « création variétale fruitière »'},
 {id:'IN-CER',title:'Le temps des cerises',url:'https://www.inrae.fr/actualites/temps-cerises',publisher:'INRAE',kind:'Recherche variétale',scope:'Folfer et Ferdouce parmi les obtentions du programme cerisier.',why:'Noms explicitement reliés au programme de sélection INRAE.',limit:'La présence dans un programme ne démontre pas l’adaptation à une parcelle.',location:'Section « Été 2007 »'},
 {id:'CT-FOL',title:'Fiche variétale Folfer',url:'https://varietes_cerise.ctifl.fr/fiche/varietes/FOLFERCOV',publisher:'CTIFL',kind:'Évaluation variétale',scope:'Floraison et maturité relatives à Burlat, pollinisation et limites de Folfer.',why:'Fiche technique issue du réseau national d’évaluation.',limit:'Dates relatives à Burlat et zones de référence ; vérifier le comportement local.',location:'Époque de maturité, floraison et pollinisation, appréciations générales'},
 {id:'CT-PRU',title:'Variétés de prunes de table',url:'https://www.ctifl.fr/les-varietes-de-prunes-de-table-les-reconnaitre-pour-mieux-les-apprecier-et-les-valoriser-point-sur-le-29',publisher:'CTIFL',kind:'Synthèse variétale',scope:'Reine-Claude, mirabelles et quetsches comme groupes de prunes traditionnelles.',why:'Repérage des principaux types dans une synthèse de centre technique.',limit:'Ne décrit ni le cultivar précis, ni sa pollinisation.',location:'Résumé de la publication'},
 {id:'CT-PRUNOMS',title:'Certification fruitière : cultivars et variétés',url:'https://varietes_cerise.ctifl.fr/Media/Page/31/Publiee/Certif%202014-2015%20WEB.pdf',publisher:'CTIFL',kind:'Liste de matériel végétal',scope:'Noms Mirabelle de Nancy, Quetsche d’Alsace et Reine-Claude.',why:'Liste institutionnelle qui confirme les dénominations retenues.',limit:'Liste de certification ancienne ; elle ne précise ni disponibilité actuelle ni adaptation locale.',location:'Tableau Prunier domestique'},
 {id:'CT-ABR',title:'Fiches variétales abricot : variétés précoces',url:'https://varietes_abricot.ctifl.fr/liste/precoce',publisher:'CTIFL',kind:'Évaluation variétale',scope:'Tom Cot classé parmi les variétés précoces.',why:'Classement variétal du réseau CTIFL.',limit:'La précocité est relative aux autres variétés, pas une date locale de récolte.',location:'Liste « Précoce »'},
 {id:'CT-BER',title:'Bergeval en agriculture biologique',url:'https://varietes_abricot.ctifl.fr/fiche/varietes-bio/bergeval-aviclo-cov',publisher:'CTIFL',kind:'Évaluation variétale',scope:'Autofertilité, floraison tardive et maturité de saison de Bergeval.',why:'Fiche issue d’évaluations et d’avis de producteurs bio.',limit:'Résultats situés dans les bassins étudiés et observations datées ; ne constituent pas une garantie locale.',location:'Identité, floraison, époque de maturité, points positifs et négatifs'},
 {id:'IN-PEC',title:'Création variétale Prunus',url:'https://gafl.paca.hub.inrae.fr/nos-resultats/creation-varietale-innovation/creation-varietale-prunus',publisher:'INRAE · GAFL',kind:'Recherche variétale',scope:'Pêcher Platibelle et contexte des créations variétales Prunus.',why:'Description institutionnelle de Platibelle.',limit:'Les performances publiées ne préjugent pas du résultat dans un autre contexte.',location:'Présentation de Platibelle'},
 {id:'IN-PECL',title:'Liste de créations variétales Prunus',url:'https://gafl.paca.hub.inrae.fr/content/download/3286/34158?version=1',publisher:'INRAE · GAFL',kind:'Liste d’obtentions',scope:'Caprice parmi les variétés de pêcher.',why:'Dénomination attestée par une liste institutionnelle.',limit:'La liste ne fournit pas de calendrier ni de comportement agronomique exploitable ici.',location:'Tableau PÊCHER'},
 {id:'IN-NOI',title:'Café Agro : fruits à coque',url:'https://ueri.paca.hub.inrae.fr/actualites/cafe-agro-fruits-a-coque',publisher:'INRAE',kind:'Retour d’essai',scope:'Corabel en collection variétale à la SENuRA.',why:'Observation d’un organisme de recherche sur le noisetier.',limit:'Le qualificatif « noisette de table » ne donne pas de résultat agronomique local.',location:'Section « Le noisetier, une espèce adaptée localement »'},
 {id:'BS-NOI',title:'Bulletin de santé du végétal : noisette',url:'https://rdf.codex.cati.inrae.fr/bsv/files/pdf/Q1179/2012/BSV_N_08-Noisette-27.04.2012.pdf',publisher:'Réseau BSV Sud-Ouest · diffusion INRAE',kind:'Observation sanitaire',scope:'Ennis présent dans des parcelles de référence.',why:'Atteste la variété dans un suivi de terrain.',limit:'Ancien bulletin sanitaire ; aucune conclusion générale sur la performance d’Ennis n’est reprise.',location:'Tableau des parcelles de référence, page 5'},
 {id:'RH-FIG',title:'Guide de culture du figuier',url:'https://www.rhs.org.uk/fruit/figs/grow-your-own',publisher:'Royal Horticultural Society',kind:'Guide horticole',scope:'Brown Turkey, White Marseilles et Little Miss Figgy.',why:'Variétés décrites par une institution horticole.',limit:'Conseils établis pour le Royaume-Uni ; ne transférez pas les dates et rendements sans validation locale.',location:'Recommended Varieties'},
 {id:'IN-AMA',title:'Des amandes françaises et agroécologiques',url:'https://www.inrae.fr/actualites/amandes-francaises-agroecologiques',publisher:'INRAE',kind:'Retour de recherche',scope:'Ferragnès, Lauranne et Mandaline en vergers partenaires.',why:'Variétés explicitement citées par INRAE.',limit:'La présence dans des vergers ne qualifie pas à elle seule la pollinisation ni la maturité.',location:'Plantations et variétés'},
 {id:'IN-AMAF',title:'Café Agro : floraison de l’amandier',url:'https://ueri.paca.hub.inrae.fr/actualites/cafe-agro-fruits-a-coque',publisher:'INRAE',kind:'Retour d’essai',scope:'Floraison de Lauranne et Ferragnès, autofertilité de Lauranne.',why:'Observation située en France qui précise un risque de gel floral.',limit:'Dates observées dans les sites cités ; floraison variable selon année et lieu.',location:'Section « L’amandier »'},
 {id:'RH-COG',title:'Guide de culture du cognassier',url:'https://www.rhs.org.uk/fruit/quince/grow-your-own',publisher:'Royal Horticultural Society',kind:'Guide horticole',scope:'Meech’s Prolific, Vranja et Serbian Gold.',why:'Variétés décrites par une institution horticole.',limit:'Appréciations en contexte britannique ; résistance ou précocité non garanties ailleurs.',location:'Recommended Varieties'},
 {id:'CT-KAK',title:'Guide des fruits exotiques : kaki',url:'https://guiderhd.ctifl.fr/fiche/fruits/fruits-exotiques',publisher:'CTIFL',kind:'Fiche filière',scope:'Fuyu et Rojo Brillante ; traitement post-récolte du type Persimon.',why:'Source technique française distinguant variété et appellation commerciale.',limit:'Information surtout commerciale et relative aux origines citées, pas essai de culture local.',location:'Section Kaki, variétés et maturité'},
 {id:'GE-V',title:'Catalogue officiel des variétés fruitières',url:'https://www.geves.fr/catalogue/',publisher:'GEVES',kind:'Référence réglementaire',scope:'Distinction entre dénomination variétale, inscription et commercialisation.',why:'Cadre officiel pour vérifier les dénominations et le statut avant achat.',limit:'La présence au catalogue n’établit ni disponibilité du plant ni adaptation à votre parcelle.',location:'Espèces fruitières et listes 1 et 2'},
 {id:'CT-POM',title:'Pomme : espèces et types commerciaux',url:'https://equipementsfruitsetlegumes.ctifl.fr/fiche/fruits-et-legumes/pomme',publisher:'CTIFL',kind:'Fiche technique',scope:'Golden Delicious, Gala et Granny Smith ; distinction entre types commerciaux, variétés et sélections de Gala.',why:'La fiche du centre technique atteste les dénominations et leur classement.',limit:'Fiche consacrée au fruit après récolte ; ses types commerciaux ne donnent ni porte-greffe, ni calendrier local de floraison ou de récolte.',location:'« Espèce et types commerciaux », tableau Variétés'},
 {id:'CT-GOLD',title:'Pommier Da Rosa / Golden Parsi',url:'https://www.ctifl.fr/pommier-da-rosa-golden-parsi-cov-infos-ctifl-401',publisher:'CTIFL',kind:'Évaluation variétale',scope:'Golden Delicious et ses sélections distinctes.',why:'Précise que plusieurs sélections commerciales dérivent de Golden Delicious.',limit:'La description des sélections ne démontre pas la performance du cultivar de base dans un lieu donné.',location:'Introduction sur Golden Delicious et les sélections'}
].map(s=>({...s,consulted:s.id.startsWith('CT-')&&['CT-POM','CT-GOLD'].includes(s.id)?'2026-10-01':'2026-09-30'}));

export const varieties = [
 {species:'pommier',name:'Ariane',summary:'Obtention INRAE sélectionnée pour une résistance aux races communes de tavelure ; résistance contournable.',flowering:'Environ 3 jours avant Golden Delicious',ripening:'Même période que Golden Delicious',source:'IN-POM'},
 {species:'pommier',name:'Story / Inored',summary:'Obtention liée au programme INRAE de sélection pour la résistance à la tavelure.',source:'IN-POM'},
 {species:'pommier',name:'Belchard / Chantecler',summary:'Obtention INRAE issue de Golden Delicious et Reinette Clochard.',source:'IN-POM'},
 {species:'poirier',name:'Angys / Angelys',summary:'Variété citée parmi les créations fruitières de l’IRHS.',source:'IN-POI'},
 {species:'poirier',name:'Migo / Cepuna',summary:'Variété citée parmi les créations fruitières de l’IRHS.',source:'IN-POI'},
 {species:'cerisier',name:'Folfer',summary:'Autostérile selon le CTIFL ; choisir un pollinisateur compatible.',flowering:'2 à 6 jours avant Burlat',ripening:'7 à 13 jours après Burlat',source:'CT-FOL'},
 {species:'cerisier',name:'Ferdouce',summary:'Variété issue du programme de sélection cerisier INRAE.',source:'IN-CER'},
 {species:'prunier',name:'Reine-Claude dorée',summary:'Prune traditionnelle de type Reine-Claude.',source:'CT-PRU'},
 {species:'prunier',name:'Mirabelle de Nancy',summary:'Dénomination répertoriée dans la liste de certification fruitière du CTIFL.',source:'CT-PRUNOMS'},
 {species:'prunier',name:'Quetsche d’Alsace',summary:'Dénomination répertoriée dans la liste de certification fruitière du CTIFL.',source:'CT-PRUNOMS'},
 {species:'abricotier',name:'Bergeval / Aviclo',summary:'Autofertile dans l’évaluation CTIFL ; floraison tardive et maturité de saison.',flowering:'Tardive, relativement aux variétés évaluées',ripening:'De saison, dans le classement CTIFL',source:'CT-BER'},
 {species:'abricotier',name:'Tom Cot / Toyaco',summary:'Classé parmi les abricots précoces par le CTIFL.',ripening:'Précoce, relativement aux variétés évaluées',source:'CT-ABR'},
 {species:'pecher',name:'Platibelle',summary:'Pêche plate à chair blanche issue du programme INRAE.',source:'IN-PEC'},
 {species:'pecher',name:'Caprice',summary:'Variété de pêcher citée dans la liste de créations variétales INRAE.',source:'IN-PECL'},
 {species:'noisetier',name:'Corabel',summary:'Noisette de table présente dans la collection variétale SENuRA décrite par INRAE.',source:'IN-NOI'},
 {species:'noisetier',name:'Ennis',summary:'Variété suivie dans des parcelles de référence du bulletin de santé du végétal.',source:'BS-NOI'},
 {species:'figuier',name:'Brown Turkey',summary:'Variété citée par la RHS pour sa fructification en contexte britannique.',source:'RH-FIG'},
 {species:'figuier',name:'White Marseilles',summary:'Grosses figues vert pâle décrites par la RHS.',source:'RH-FIG'},
 {species:'figuier',name:'Little Miss Figgy / Lmf01',summary:'Variété compacte décrite par la RHS pour la culture en contenant.',source:'RH-FIG'},
 {species:'amandier',name:'Lauranne',summary:'Variété autofertile ; la floraison reste exposée au gel.',flowering:'Fin février–début mars dans les sites INRAE cités',source:'IN-AMAF'},
 {species:'amandier',name:'Ferragnès',summary:'Variété présente dans les vergers partenaires décrits par INRAE.',flowering:'Fin février–début mars dans les sites INRAE cités',source:'IN-AMAF'},
 {species:'amandier',name:'Mandaline',summary:'Variété issue des programmes de sélection INRAE et présente dans les vergers partenaires.',source:'IN-AMA'},
 {species:'cognassier',name:'Meech’s Prolific',summary:'Production abondante et fruits jaunes en forme de poire selon la RHS.',source:'RH-COG'},
 {species:'cognassier',name:'Vranja',summary:'Variété relativement précoce dans le guide RHS.',ripening:'Précoce, relativement aux variétés du guide RHS',source:'RH-COG'},
 {species:'cognassier',name:'Serbian Gold',summary:'Variété compacte avec tolérance à la brûlure des feuilles observée dans la collection RHS Wisley.',source:'RH-COG'},
 {species:'kaki',name:'Fuyu',summary:'Type de kaki aplati et légèrement côtelé cité par le CTIFL.',source:'CT-KAK'},
 {species:'kaki',name:'Rojo Brillante',summary:'Variété à l’origine du kaki commercial Persimon ; la réduction de l’astringence fait intervenir un traitement post-récolte.',ripening:'Octobre–novembre pour la production espagnole décrite',source:'CT-KAK'},
 {species:'pommier',name:'Florina / Querina',summary:'Pomme à couteau citée par INRAE parmi les variétés sélectionnées pour une moindre sensibilité aux maladies.',source:'IN-POM'},
 {species:'pommier',name:'Antarès / Dalinbel',summary:'Pomme à couteau citée par INRAE parmi les variétés sélectionnées pour une moindre sensibilité aux maladies.',source:'IN-POM'},
 {species:'pommier',name:'Choupette / Dalinette',summary:'Pomme à couteau citée par INRAE parmi les variétés sélectionnées pour une moindre sensibilité aux maladies.',source:'IN-POM'},
 {species:'pommier',name:'Golden Delicious',summary:'Variété de pomme de type jaune ; le CTIFL distingue ses sélections commerciales du cultivar de référence.',source:'CT-GOLD'},
 {species:'pommier',name:'Gala',summary:'Groupe variétal de pommes bicolores ; Royal Gala et Galaxy sont des sélections citées séparément par le CTIFL.',source:'CT-POM'},
 {species:'pommier',name:'Granny Smith',summary:'Variété de pomme classée dans le type vert par le CTIFL.',source:'CT-POM'}
].map((entry,index)=>({id:`cv-${index+1}`,flowering:null,ripening:null,...entry}));

// Une seconde lecture indépendante est conservée séparément de la source technique.
// Les descriptions commerciales ne modifient pas les faits retenus sans examen.
export const nurserySources = [
 {id:'PE-ARI',title:'Pommier Ariane',url:'https://www.promessedefleurs.com/fruitiers/fruitiers-par-variete/pommier/pommier-ariane-malus-domestica.html',publisher:'Promesse de Fleurs',scope:'Nom Ariane et description horticole.',location:'Fiche produit, description',limit:'Description de vente ; porte-greffe et conditions de culture peuvent changer les résultats.'},
 {id:'PE-ANG',title:'Poirier Angelys',url:'https://www.promessedefleurs.com/fruitiers/fruitiers-par-variete/poirier/poirier-angelys.html',publisher:'Promesse de Fleurs',scope:'Nom Angelys, récolte annoncée en octobre et pollinisation non autofertile.',location:'Fiche produit, floraison et récolte',limit:'Mois indicatif du catalogue, dépendant de la région et de l’année.'},
 {id:'PB-FOL',title:'Cerisier Folfer',url:'https://pepinieredubosc.fr/nos-arbres-fruitiers/cerisier-folfer/',publisher:'Pépinière du Bosc',scope:'Nom Folfer ; la fiche indique « autofertile », en désaccord avec le CTIFL.',location:'Description, rubrique autofertilité',limit:'Information commerciale contradictoire avec le profil allélique et la conclusion CTIFL ; vérifier auprès du fournisseur.'},
 {id:'PE-MIR',title:'Prunier Mirabelle de Nancy',url:'https://www.promessedefleurs.com/fruitiers/fruitiers-par-variete/prunier-mirabelle/prunier-mirabelle-de-nancy.html',publisher:'Promesse de Fleurs',scope:'Nom Mirabelle de Nancy ; floraison mars–avril et récolte août–septembre annoncées.',location:'Fiche produit, calendrier',limit:'La même enseigne emploie ailleurs « partiellement autofertile » ; ne pas conclure sur la pollinisation sans vérification.'},
 {id:'ES-BER',title:'Catalogue fruits à noyau',url:'https://www.pepinieres-escande.com/wp-content/uploads/Catalogue-Noyaux-0921.pdf',publisher:'Pépinières Escande',scope:'Bergeval / Aviclo annoncé autofertile, récolte mi-juin à fin juin dans les Costières.',location:'Tableau abricotiers, ligne Bergeval',limit:'Catalogue daté de 2021 ; dates situées dans la zone des Costières.'},
 {id:'SR-PLA',title:'Pêcher Platibelle',url:'https://www.pepinieres-saint-romas.fr/pecher/',publisher:'Pépinières Saint Romas',scope:'Platibelle décrit comme pêche plate blanche, avec dates distinctes nord/sud de la France.',location:'Rubrique PLATIBELLE',limit:'Dates commerciales indicatives, sans protocole d’essai documenté.'},
 {id:'CO-COR',title:'Noisetier Corabel',url:'https://www.coulie.com/portfolios/corabel/',publisher:'Pépinières Coulié',scope:'Corabel présenté comme noisette de table, à maturité tardive.',location:'Appréciations générales',limit:'Appréciation de pépinière, sans données comparatives locales.'},
 {id:'PE-FIG',title:'Figuier Brown Turkey',url:'https://www.promessedefleurs.com/fruitiers/fruitiers-par-variete/figuier/figuier-brown-turkey.html',publisher:'Promesse de Fleurs',scope:'Nom Brown Turkey et description de ses fruits.',location:'Fiche produit, description',limit:'Fiche commerciale ; fructification et vigueur changent selon le climat.'},
 {id:'PE-LAU',title:'Amandier Lauranne',url:'https://www.promessedefleurs.com/fruitiers/fruitiers-de-a-a-z/amandier-lauranne-autofertile-prunus-dulcis.html',publisher:'Promesse de Fleurs',scope:'Nom Lauranne / Avijor et autofertilité.',location:'Fiche produit, description',limit:'Les dates de floraison et seuils de froid affichés sont indicatifs ; le gel floral diffère de la rusticité du bois.'},
 {id:'PE-VRA',title:'Cognassier Vranja',url:'https://www.promessedefleurs.com/fruitiers/fruitiers-par-variete/cognassier/cognassier-commun-cydonia-oblonga-vranja.html',publisher:'Promesse de Fleurs',scope:'Nom Vranja / Monstrueux de Vranja et calendrier horticole.',location:'Fiche produit, description',limit:'Évaluation commerciale ; dates variables suivant site.'},
 {id:'PB-ROJ',title:'Kaki Rojo Brillante',url:'https://pepinieredubosc.fr/nos-arbres-fruitiers/plaqueminier-rojobrillant-ou-persimon/',publisher:'Pépinière du Bosc',scope:'Distinction Rojo Brillante / Fuyu et nécessité du blettissement ou d’un traitement pour réduire l’astringence.',location:'Rubrique différence avec Fuyu',limit:'Fiche de vente ; le calendrier de maturation dépend du climat.'},
 {id:'PE-GOL',title:'Pommier Golden Delicious',url:'https://www.promessedefleurs.com/fruitiers/fruitiers-par-variete/pommier/pommier-golden-delicious.html',publisher:'Promesse de Fleurs',scope:'Dénomination Golden Delicious et description du fruit.',location:'Fiche produit, description',limit:'Calendrier et pollinisateurs annoncés commercialement ; non retenus comme données techniques locales.'},
 {id:'PE-GAL',title:'Pommier Gala',url:'https://www.promessedefleurs.com/fruitiers/fruitiers-par-variete/pommier/pommier-malus-domestica-gala.html',publisher:'Promesse de Fleurs',scope:'Dénomination Gala et description du fruit.',location:'Fiche produit, description',limit:'La fiche ne précise pas la sélection du groupe Gala ni un protocole de datation local.'},
 {id:'PE-GRA',title:'Pommier Granny Smith',url:'https://www.promessedefleurs.com/fruitiers/fruitiers-par-variete/pommier/pommier-granny-smith.html',publisher:'Promesse de Fleurs',scope:'Dénomination Granny Smith et fruit vert.',location:'Fiche produit, description',limit:'Les mois et seuils thermiques commerciaux ne sont pas repris comme valeurs générales.'}
].map(s=>({...s,kind:'Fiche de pépinière',why:'Seconde lecture de la dénomination ou d’un caractère variétal.',consulted:['PE-GOL','PE-GAL','PE-GRA'].includes(s.id)?'2026-10-01':'2026-09-30'}));

export const nurseryCrosschecks = {
 'cv-1':{source:'PE-ARI',note:'Dénomination et description recoupées.'},
 'cv-4':{source:'PE-ANG',note:'Dénomination recoupée ; récolte annoncée en octobre par la pépinière.'},
 'cv-6':{source:'PB-FOL',note:'Désaccord sur la pollinisation : CTIFL autostérile, pépinière autofertile. Vérifier un pollinisateur compatible avant plantation.',status:'conflict'},
 'cv-9':{source:'PE-MIR',note:'Dénomination recoupée ; la pépinière annonce mars–avril pour la floraison et août–septembre pour la récolte. Ses pages divergent sur l’autofertilité.'},
 'cv-11':{source:'ES-BER',note:'Autofertilité concordante ; récolte mi-juin à fin juin en Costières selon le catalogue 2021.'},
 'cv-13':{source:'SR-PLA',note:'Pêche plate blanche concordante ; dates nord/sud annoncées par la pépinière.'},
 'cv-15':{source:'CO-COR',note:'Noisette de table concordante ; maturité tardive dans le catalogue de pépinière.'},
 'cv-17':{source:'PE-FIG',note:'Dénomination et description du fruit recoupées.'},
 'cv-20':{source:'PE-LAU',note:'Autofertilité concordante ; la date de floraison de la pépinière diffère du site INRAE.'},
 'cv-24':{source:'PE-VRA',note:'Dénomination Vranja / Monstrueux de Vranja recoupée.'},
 'cv-27':{source:'PB-ROJ',note:'Le caractère astringent et le traitement post-récolte sont cohérents avec le CTIFL.'},
 'cv-31':{source:'PE-GOL',note:'Dénomination recoupée ; la date commerciale de récolte reste indicative.'},
 'cv-32':{source:'PE-GAL',note:'Dénomination recoupée ; sélectionner un clone précis avant achat.'},
 'cv-33':{source:'PE-GRA',note:'Dénomination et type vert recoupés ; le calendrier commercial reste indicatif.'}
};
